server:
    port: 8761

security:
    user:
        password: ${eureka.password}

info:
    component: Discovery Server

eureka:
    client:
        registerWithEureka: false
        fetchRegistry: false
    server:
        waitTimeInMsWhenSyncEmpty: 0
    password: ${SECURITY_USER_PASSWORD:password}

logging:
    level:
        ROOT: WARN

---
spring:
    profiles: docker1
eureka:
    instance:
        hostname: discovery
    client:
        registerWithEureka: false
        fetchRegistry: false