server:
    port: 8761

security:
    user:
        password: ${eureka.password}

info:
    component: Discovery Server

eureka:
    client:
        registerWithEureka: false
        fetchRegistry: false
    server:
        waitTimeInMsWhenSyncEmpty: 0
    password: ${SECURITY_USER_PASSWORD:password}

logging:
    level:
        ROOT: WARN

---
spring:
    profiles: docker1
eureka:
    instance:
        hostname: discovery1
    client:
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl:
            defaultZone: http://user:${eureka.password}@discovery2:8762/eureka/

---
spring:
    profiles: docker2
server:
    port: 8762
eureka:
    instance:
        hostname: discovery2
        nonSecurePort: ${server.port}
    client:
        serviceUrl:
            defaultZone: http://user:${eureka.password}@localhost:8762/eureka/
